# Generated by Django 5.2.2 on 2025-06-09 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do post', max_length=200, verbose_name='Título')),
                ('content', models.TextField(help_text='Conteúdo do post (HTML ou Markdown)', verbose_name='Conteúdo')),
                ('slug', models.SlugField(blank=True, help_text='URL amigável do post (gerada automaticamente se vazia)', max_length=200, unique=True, verbose_name='Slug')),
                ('is_published', models.BooleanField(default=False, help_text='Define se o post está publicado', verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='cms_post_created_a785be_idx'), models.Index(fields=['slug'], name='cms_post_slug_90607d_idx'), models.Index(fields=['is_published'], name='cms_post_is_publ_9ff455_idx')],
            },
        ),
    ]
