# Generated by Django 5.2.2 on 2025-06-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Chave única para identificar a configuração', max_length=100, unique=True)),
                ('value', models.TextField(blank=True, help_text='Valor da configuração', null=True)),
                ('default_value', models.TextField(blank=True, help_text='Valor padrão da configuração', null=True)),
                ('category', models.CharField(choices=[('site', 'Configurações do Site'), ('seo', 'Configurações de SEO'), ('email', 'Configurações de Email'), ('media', 'Configurações de Mídia'), ('general', 'Configurações Gerais'), ('social', 'Redes Sociais'), ('analytics', 'Analytics')], default='general', help_text='Categoria da configuração', max_length=20)),
                ('type', models.CharField(choices=[('text', 'Texto'), ('textarea', 'Texto Longo'), ('number', 'Número'), ('boolean', 'Verdadeiro/Falso'), ('email', 'Email'), ('url', 'URL'), ('json', 'JSON'), ('file', 'Arquivo')], default='text', help_text='Tipo de dado da configuração', max_length=20)),
                ('label', models.CharField(help_text='Nome amigável da configuração', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descrição da configuração', null=True)),
                ('is_required', models.BooleanField(default=False, help_text='Se a configuração é obrigatória')),
                ('is_public', models.BooleanField(default=False, help_text='Se a configuração pode ser acessada publicamente')),
                ('order', models.IntegerField(default=0, help_text='Ordem de exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
                'ordering': ['category', 'order', 'label'],
            },
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='cms_post_created_a785be_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='cms_post_slug_90607d_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='cms_post_is_publ_9ff455_idx',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Conteúdo completo do post', verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Se o post está publicado e visível publicamente', verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='URL amigável (será gerada automaticamente se não fornecida)', max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
