# Generated by Django 5.2.2 on 2025-06-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_siteconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Recebida em')),
            ],
            options={
                'verbose_name': 'Mensagem de Contato',
                'verbose_name_plural': 'Mensagens de Contato',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='category',
            field=models.CharField(choices=[('site', 'Site'), ('email', 'Email'), ('seo', 'SEO'), ('social', 'Redes Sociais'), ('outros', 'Outros')], default='outros', max_length=50),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='default_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='label',
            field=models.CharField(max_length=150, verbose_name='Rótulo'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='type',
            field=models.CharField(choices=[('text', 'Texto'), ('textarea', 'Área de texto'), ('number', 'Número'), ('boolean', 'Booleano'), ('email', 'Email'), ('url', 'URL'), ('json', 'JSON')], default='text', max_length=50),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
